### ISSUE TITLE
CircleCI: x509 system root certs missing

### ISSUE THREAD

**Issue by tie** [philoserf/pandoc#30]
I'm getting the following error on *persist_to_workspace* step inside a CircleCI job:

>*Error uploading workspace archive: RequestError: send request failed
caused by: Put __https s3.amazonaws.com URL placeholder__: x509: failed to load system roots and no roots provided*

The reason is that CI uses Go's *tls* package which [looks for certificates][1] in */etc/ssl/certs/ca-certificates.crt*.  However, this file is missing in the image (well, */etc/ssl/certs* directory is empty).

I've fixed the issue by running `cp /etc/ssl/cert.pem /etc/ssl/certs/ca-certificates.crt` inside the image.

That said, it would be nice if you can create a symlink for convenience (and to save time of other CircleCI users).

[1]: https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07#deec

**Comment by philoserf** [comment]
I will take a look. Can you share a `docker run` example of the error?

**Comment by philoserf** [comment]
I used to have a range of certs and all of LaTeX in the image but it was huge. Seems I've slimmed down too far..

**Comment by tie** [comment]
>Can you share a `docker run` example of the error?

Sorry, I don't have docker installed.

It should be possible to reproduce the error with the following cirlceci config:

```yaml
version: 2.0
jobs:
  build:
    docker:
    - image: philoserf/pandoc:v1.2.0
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
        - README.md
```

> Seems I've slimmed down too far..
